# Generated by Django 3.1.4 on 2021-03-21 05:06

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('meat_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_to_meat', to='customer.meat')),
            ],
        ),
        migrations.CreateModel(
            name='TablestableInStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='CLOSE', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tabledailydate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_open_time', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=5)),
                ('people_count', models.IntegerField()),
                ('table_close_time', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_of_dailytable', to='customer.tablestableinstore')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('status', models.CharField(choices=[('ORDERED', 'ORDERED'), ('SERVED', 'SERVED')], default='ORDERED', max_length=7)),
                ('serve_time', models.DateTimeField(blank=True, null=True)),
                ('meat', models.ManyToManyField(related_name='meat_reciept', through='customer.OrderReciept', to='customer.Meat')),
                ('table', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_table', to='customer.tabledailydate')),
            ],
        ),
        migrations.AddField(
            model_name='orderreciept',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_to_order', to='customer.orders'),
        ),
        migrations.AddField(
            model_name='meat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_meat', to='customer.typeofmeat'),
        ),
    ]
