# Generated by Django 3.1.4 on 2021-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='meat_img',
            field=models.ImageField(default='', upload_to='images/meat/'),
        ),
    ]
