# Generated by Django 3.1.4 on 2021-01-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orders_meats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
