# Generated by Django 3.1.4 on 2021-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_tablestableinstore_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestableinstore',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='CLOSE', max_length=5),
        ),
    ]
