# Generated by Django 3.1.4 on 2021-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='meat',
            field=models.ManyToManyField(related_name='meat_reciept', through='customer.OrderReciept', to='customer.Meat'),
        ),
    ]
