# Generated by Django 3.1.4 on 2021-02-07 12:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='meat_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
