# Generated by Django 3.1.4 on 2021-03-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210313_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreciept',
            name='meat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_meat', to='customer.meat'),
        ),
    ]
